dirs
leave town
put hands in pockets
remove hands from pockets
put both hands in pockets
get hands from pockets
put all in pockets
take hands out of pockets
take hands from pockets
take all from pockets
rub left hand on right hand
clean left hand with right hand
rub left hand on left hand
put right hand on right hand
put left hand in right hand
put left hand in left hand
lift left hand with right hand
lift left hand with left hand
unlock right hand with right hand
unlock right hand with left hand
unlock left hand with right hand
unlock left hand with left hand
unlock buildings with left hand
unlock buildings with right hand
search self
change mind
give bag to self
say prayer to motorcycle gods
read self
visit bike
x bike
x battery
x chain
untie chain
wake up
wake bike up
x buildings
search street
search buildings
move rubble
search rubble
take some stones
pray on roof
pray to god on roofs
ne
pray to advertisement
x board
search board
read board
look under board
x drifts
dig drifts
x markers
take markers
look under road
dig road
x tar
take the path to the south
go south
x square
x buildings
search buildings
search square
x church roof
x church spire
x church bell
search dwellings
e
x church
x graffiti
search graffiti
e
search church
x doors
listen at gap
rub gap
pull knob
twist knob
touch knob
touch door
unlock door
unlock church building with left hand
unlock church building with right hand
push door
pick the lock
pick litter
collect waste
pick door
listen at doors
look between doors
x latch
say prayers
pray that game ends
pray that bed appears
pray that doors open
pray to God that door opens
pray to God that doors open
pray to God for doors to open
x back doors
x tympanum
x archway
x stained glass
x clothes
search clothes
x pockets
x shirt pocket
x trouser pockets
search trouser pockets
search pockets
x card  
blow card
remove card from bag
drop card
unlock church door
unlock latch
open church door with card
unlock church door
unlock latch with card
use card on latch
push door
close church door
lift latch with card
pull church door
close latch
lift latch
use latch
use card
use card on latch
lock latch
raise latch with card
e
enter church
x latch
search doors
push latch inwards
close latch
lock latch
explore church
search shadows
x shadow
get window
x windows
undo knot
push knot
push knot up
push knot out
push knot outwards
push knot to west
push knot west
twist cord
untie cord
pull knot
x cord
search dangling bellcord
swing on rope
climb rope
x bell tower
x church bell
take bell
cut rope
cut rope with card
push doors
open doors
lift latch
pull knob
sit down
x architecture
x pipe organ
x rood screen
go into crypt
x baptismal font
search apse
search sanctuary
climb up
search presbytery
say confession
confess sins
talk to priest
sleep
sleep in porch
sleep in ambulatory
make fire
make bed
search bag
touch bag
smell bag
say prayers
make bed on floor
sleep on ground
make bed with supplies
undo
x altar
pray at altar
jump over altar
sleep on altar
jump on altar
climb on altar
sleep on altar
look under altar
x altar legs
jump over pews
jump
listen
sleep on pew
sit in pew
kiss pews
touch door
look under pews
take cushion
taste cushion
make bed from cushions
put cushion in aisle
throw cushion at windows
make bed with camping gear
undo
drop belongings
open bag
take file
x file
read file
unstrap file
transfer bag to pew
sit down
open file
read file
search file
look up goat in file
get up
take bag
put file away
drop file
make bed
undo
exit church building
leave
x trash
insert card in trashcan
put bag in dustbin
clear ground
clean waste
transfer waste to trash-can
search bin
shout
go behind church
go around church building
search passage
climb over bins
smell bins
shift bins
se
1
1
1
1
1
1
2
1
1
1
0
w
x side door
s
n
x garden gate
x garden
jump over gate
climb gate
put papers on can
visit Ben
wake Ben up
buy food from Ben
taste Ben
x Ben's vegetables
take veg
steal Ben's veggies
take Ben
twist Ben
jump over Ben
wave card at Ben
show card to Ben
give bag to Ben
Ben, taste the upturned can
listen to Ben
squeeze Ben
hug Ben
talk to person
2
2
4
4
4
4
4
3
2
2
follow Ben
g
g
g
g
g
g
