dirs
search self
change mind
give bag to self
say prayer to motorcycle gods
read self
visit bike
x bike
x buildings
search street
search buildings
move rubble
search rubble
take stones
pray on roof
pray to god on roofs
ne
pray to advertisement
x board
search board
read board
look under board
x drifts
dig drifts
x markers
take markers
look under road
dig road
x tar
take the path to the south
go south
x square
x buildings
search buildings
search square
x church roof
x church spire
x church bell
search dwellings
x church
x graffiti
search graffiti
x doors
listen at gap
rub gap
pull knob
twist knob
touch knob
touch door
push door
pick the lock
pick litter
collect waste
pick door
listen at doors
look between doors
x latch
say prayers
pray that game ends
pray that bed appears
pray that doors open
pray to God that door opens
pray to God that doors open
pray to God for doors to open
x back doors
x tympanum
x archway
x stained glass
x clothes
search clothes
x pockets
x shirt pocket
x trouser pockets
search trouser pockets
x card  
remove card from bag
drop card
open church door with card
push door
close church door
lift latch with card
pull church door
lift latch
raise latch with card
enter church
x latch
search doors
push latch inwards
get window
x windows
undo knot
push knot
push knot up
push knot out
push knot outwards
push knot to west
push knot west
twist cord
pull knot
x cord
search dangling bellcord
swing on rope
climb rope
x bell tower
x church bell
take bell
cut rope
cut rope with card
push doors
lift latch
pull knob
sit down
x architecture
x pipe organ
x rood screen
go into crypt
x baptismal font
search apse
search sanctuary
climb up
search presbytery
say confession
confess sins
talk to priest
sleep
sleep in porch
sleep in ambulatory
make fire
make bed
search bag
touch bag
smell bag
say prayers
make bed on floor
sleep on ground
make bed with supplies
undo
x altar
pray at altar
jump over altar
sleep on altar
jump on altar
climb on altar
sleep on altar
look under altar
x altar legs
jump over pews
jump
listen
sleep on pew
sit in pew
kiss pews
touch door
look under pews
take cushion
taste cushion
make bed from cushions
put cushion on pew
throw cushion at windows
make bed with camping gear
undo
drop belongings
open bag
take file
x file
read file
unstrap file
transfer bag to pew
sit down
open file
read file
search file
look up foo in file
get up
take bag
put file away
drop file
make bed
undo
exit church building
leave
se
x trash
insert card in trashcan
put bag in dustbin
clear ground
clean waste
transfer waste to trash-can
search bin
pull bin
shout
go behind church
go around church building
se
smell bins
shift bins
again
g
g
smell bins
se
1
1
1
1
1
1
2
1
1
1
0
w
x side door
s
n
jump over gate
climb gate
put papers on can
visit Ben
talk to person
2
2
4
4
4
4
4
3
2
2
follow Ben
g
g
g
g
g
g
